### PR TITLE
Add passive virtour to all segbot launch files

### PR DESCRIPTION
**Pull request by pato**

### CODE REVIEW

**Comment by pato** [comment]
@jack-oquin  - I am having troubles getting this to pass the CI tests. It seems it cannot find `bwi_virtour`. I thought it would pass once you released the latest version of `bwi_common`.
I also tried what you did on the led PR (https://github.com/utexas-bwi/segbot/commit/ca1ce17b4bc616c71accc5c86e9897eed3796a32) with no success.

Any ideas?

PS: I can revert the `ros-shawdow-fixed` change if it's going to cause problems

**Comment by jack-oquin** [comment]
Those failures are not your fault. They are some bwi_launch tests failing due to the segbot repository being down-level. Now that bwi_common is released, we can release segbot. That should fix those problems.

I think we should always use ros-shadow-fixed for testing all our repositories, thanks for updating that. I was about to make the same change, myself.

**Comment by pato** [comment]
Makes sense, thanks for the fast response!
I've deleted the branch

**Comment by jack-oquin** [comment]
I am releasing segbot right now. That should fix most of the Travis problems. Then, we'll see. :smile:

**Pull request merged**
